services:
  go-server:
    restart: always
    image: golang:latest
    container_name: go-server
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    env_file:
      - .env
    command: go run main.go
    depends_on:
      - mongo
      - mailserver
      - mailserverTest

  mongo:
    restart: always
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./script/example.sh:/example.sh
      - ./script/file.js:/file.js
    env_file:
      - .env
    entrypoint: ["sh", "example.sh"]
    command: ["mongod", "--quiet"]


  mailserverTest:
    restart: always
    image: mailhog/mailhog:latest
    container_name: mailserverTest
    ports:
      - "1025:1025"
      - "8025:8025"

  mailserver:
    restart: always
    image: juanluisbaptiste/postfix:latest
    container_name: mailserver
    ports:
      - "2500:2500"
    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SERVER_HOSTNAME: ${SERVER_HOSTNAME}

volumes:
  mongo-data: