services:
  go-server:  # fetcha la configurazione lui dal db, e starta lui i containers necessari con le configurazioni prese dal db
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-server
    ports:
      - "8080:8080"
#    volumes:
#      - .:/go/src/app
#      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - postgres
#      - mongo
#      - mailserverTest
    networks:
      - mynetwork

  postgres:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - mynetwork
    
 # mailserverTest:
  #  restart: always
   # image: mailhog/mailhog:latest
    #container_name: mailserverTest
   # ports:
    #  - "1025:1025"
    #  - "8025:8025"
   # networks:
    #  - mynetwork

networks:
  mynetwork:
    driver: bridge